from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class ReferenceProject(BaseModel):
    """A past project used as calibration context for the estimation."""

    name: str = Field(description="Short name or codename of the reference project.")
    description: str = Field(
        description="What the project did in 1-2 sentences."
    )
    total_hours: int = Field(
        description="Actual hours delivered on that project."
    )
    notes: str | None = Field(
        default=None,
        description="Optional lessons learned or caveats that affect the comparison.",
    )


class ProjectType(str, Enum):
    MOBILE_APP = "mobile_app"
    WEB_SAAS = "web_saas"
    INTERNAL_TOOL = "internal_tool"
    DATA_PIPELINE = "data_pipeline"


class DetailLevel(str, Enum):
    SUMMARY = "summary"
    MEDIUM = "medium"
    DETAILED = "detailed"


class OutputFormat(str, Enum):
    PHASES_TABLE = "phases_table"
    LINE_ITEMS = "line_items"
    NARRATIVE = "narrative"


class EstimationRequest(BaseModel):
    """Payload sent by the client to request a software estimation."""

    description: str = Field(
        ...,
        min_length=20,
        max_length=2000,
        description="Description of the software project to estimate.",
        examples=[
            "The client wants a web app where users can upload CSV files and visualise the data as interactive charts. The backend should store the files in S3 and expose a REST API."
        ],
    )
    project_type: ProjectType = Field(
        description="Category of the project being estimated.",
    )
    detail_level: DetailLevel = Field(
        description="How granular the estimation breakdown should be.",
    )
    output_format: OutputFormat = Field(
        description="The structure of the estimation output.",
    )
    reference_projects: list[ReferenceProject] | None = Field(
        default=None,
        description=(
            "Optional list of past similar projects used as calibration anchors. "
            "When provided, the model will use them to ground its estimates."
        ),
        examples=[
            [
                {
                    "name": "Acme CRM",
                    "description": "Internal CRM for a 50-person sales team.",
                    "total_hours": 320,
                    "notes": "Heavy custom reporting added 40 h.",
                }
            ]
        ],
    )


class UsageCost(BaseModel):
    """Token usage and derived cost for a single API call."""

    input_tokens: int = Field(description="Number of input tokens sent to the model.")
    output_tokens: int = Field(
        description="Number of output tokens generated by the model."
    )
    total_tokens: int = Field(description="Sum of input and output tokens.")
    cost_usd: float = Field(description="Estimated cost in USD for this request.")


class EstimationResponse(BaseModel):
    """Response returned by the API after generating the estimation.

    The estimation is returned as a Markdown-formatted string, ready to be
    rendered by any frontend or consumed as plain text.
    """

    text: str = Field(
        description="Software effort estimation in Markdown format, generated by the LLM."
    )
    prompt_version: str = Field(
        description="Version identifier of the system prompt used to generate this estimation."
    )
    provider_used: str = Field(
        description="The LLM provider that generated this estimation."
    )
    model_used: str = Field(
        description="The specific model that generated this estimation."
    )
    usage: UsageCost = Field(
        description="Token usage and estimated cost for this request."
    )
