from pydantic import BaseModel, Field


class EstimationRequest(BaseModel):
    """Payload sent by the client to request a software estimation.

    The client submits the raw text of a meeting transcription and,
    optionally, which LLM provider to use for this specific request.
    If no provider is specified, the one configured in Settings is used.
    """

    transcript: str = Field(
        ...,  # '...' means required — no default value
        min_length=20,
        max_length=10_000,
        description="Raw text of the meeting transcription to estimate.",
        examples=[
            "The client wants a web app where users can upload CSV files and visualise the data as interactive charts. The backend should store the files in S3 and expose a REST API."
        ],
    )
    provider: str | None = Field(
        default=None,
        description="LLM provider to use: 'openai' or 'anthropic'. Defaults to the value in Settings.",
        examples=["openai", "anthropic"],
    )


class UsageCost(BaseModel):
    """Token usage and derived cost for a single API call."""

    input_tokens: int = Field(description="Number of input tokens sent to the model.")
    output_tokens: int = Field(
        description="Number of output tokens generated by the model."
    )
    total_tokens: int = Field(description="Sum of input and output tokens.")
    cost_usd: float = Field(description="Estimated cost in USD for this request.")


class EstimationResponse(BaseModel):
    """Response returned by the API after generating the estimation.

    The estimation is returned as a Markdown-formatted string, ready to be
    rendered by any frontend or consumed as plain text.
    """

    estimation: str = Field(
        description="Software effort estimation in Markdown format, generated by the LLM."
    )
    provider_used: str = Field(
        description="The LLM provider that generated this estimation."
    )
    model_used: str = Field(
        description="The specific model that generated this estimation."
    )
    usage: UsageCost = Field(
        description="Token usage and estimated cost for this request."
    )
