from pydantic import BaseModel, Field


class EstimationRequest(BaseModel):
    """Payload sent by the client to request a software estimation.

    The client submits the raw text of a meeting transcription and,
    optionally, which LLM provider to use for this specific request.
    If no provider is specified, the one configured in Settings is used.
    """

    transcript: str = Field(
        ...,  # '...' means required — no default value
        min_length=20,
        max_length=10_000,
        description="Raw text of the meeting transcription to estimate.",
        examples=[
            "The client wants a web app where users can upload CSV files and visualise the data as interactive charts. The backend should store the files in S3 and expose a REST API."
        ],
    )
    provider: str | None = Field(
        default=None,
        description="LLM provider to use: 'openai' or 'anthropic'. Defaults to the value in Settings.",
        examples=["openai", "anthropic"],
    )


class UsageCost(BaseModel):
    """Token usage and derived cost for a single API call."""

    input_tokens: int = Field(description="Number of input tokens sent to the model.")
    output_tokens: int = Field(
        description="Number of output tokens generated by the model."
    )
    total_tokens: int = Field(description="Sum of input and output tokens.")
    cost_usd: float = Field(description="Estimated cost in USD for this request.")


# ---------------------------------------------------------------------------
# Structured estimation models — used by Instructor to parse the LLM response
# ---------------------------------------------------------------------------


class Task(BaseModel):
    """A single unit of work within a project phase."""

    name: str = Field(
        description="Short, descriptive name of the task (e.g. 'Design database schema')."
    )
    hours: float = Field(
        description="Estimated effort in hours required to complete this task."
    )
    cost_usd: float = Field(
        description="Estimated cost in USD for this task, calculated as hours × hourly rate."
    )


class Phase(BaseModel):
    """A logical phase or stage of the project (e.g. Discovery, Backend, QA)."""

    name: str = Field(
        description="Name of the project phase (e.g. 'Backend Development', 'QA & Testing')."
    )
    tasks: list[Task] = Field(
        description="Ordered list of tasks that belong to this phase."
    )
    total_hours: float = Field(
        description="Sum of hours across all tasks in this phase."
    )
    total_cost_usd: float = Field(
        description="Sum of costs in USD across all tasks in this phase."
    )


class TeamMember(BaseModel):
    """A role in the recommended team composition."""

    role: str = Field(
        description="Job title or role (e.g. 'Backend Engineer', 'UX Designer')."
    )
    count: int = Field(
        description="Number of people with this role needed for the project."
    )
    dedication: str = Field(
        description=(
            "Expected time dedication for this role, expressed as a percentage or description "
            "(e.g. '100%', '50% part-time', 'full-time for phases 1-3')."
        )
    )


class EstimationResult(BaseModel):
    """Structured software effort estimation produced directly by the LLM via Instructor.

    This model is used as the response_model in Instructor calls. Every field
    must be filled by the LLM; descriptions are included in the JSON Schema
    sent to the model, so keep them precise and unambiguous.
    """

    executive_summary: str = Field(
        description=(
            "A concise executive summary (3-5 sentences) of the project scope, "
            "main technical challenges, and the overall effort estimate."
        )
    )
    phases: list[Phase] = Field(
        description=(
            "Ordered list of project phases. Cover the full delivery lifecycle: "
            "e.g. Discovery, Design, Backend, Frontend, Integration, QA, Deployment."
        )
    )
    total_hours: float = Field(
        description="Grand total of estimated hours across all phases."
    )
    total_cost_usd: float = Field(
        description="Grand total estimated cost in USD across all phases."
    )
    team_composition: list[TeamMember] = Field(
        description="Recommended team composition listing each required role, headcount, and dedication."
    )
    duration_weeks: float = Field(
        description=(
            "Estimated calendar duration of the project in weeks, assuming the recommended "
            "team composition works in parallel where possible."
        )
    )


# ---------------------------------------------------------------------------
# FastAPI response model — wraps EstimationResult with provider/model/usage
# ---------------------------------------------------------------------------


class EstimationResponse(BaseModel):
    """Response returned by the API after generating the estimation."""

    estimation: EstimationResult = Field(
        description="Structured software effort estimation produced by the LLM."
    )
    provider_used: str = Field(
        description="The LLM provider that generated this estimation."
    )
    model_used: str = Field(
        description="The specific model that generated this estimation."
    )
    usage: UsageCost = Field(
        description="Token usage and estimated cost for this request."
    )
