"""Estimation router — handles POST /api/v1/estimate."""

from fastapi import APIRouter, HTTPException, status

from src.core.logging import logger
from src.schemas.estimation import EstimationRequest, EstimationResponse
from src.services.llm_service import generate_estimation

router = APIRouter(prefix="/api/v1", tags=["Estimation"])

@router.post(
    "/estimate",
    response_model=EstimationResponse,
    status_code=status.HTTP_200_OK,
    summary="Generate a software effort estimation",
    description=(
        "Receives the raw text of a meeting transcription and returns a structured "
        "software effort estimation generated by an LLM using CAG (Context-Augmented Generation)."
    ),
)
async def estimate(request: EstimationRequest) -> EstimationResponse:
    """POST /api/v1/estimate

    FastAPI automatically:
    - Parses and validates the JSON body against EstimationRequest.
    - Returns 422 if validation fails (missing fields, wrong types, etc.).
    - Serialises the returned EstimationResponse to JSON.
    """
    try:
        return await generate_estimation(
            transcript=request.transcript,
            provider_override=request.provider,
        )
    except ValueError as exc:
        # Raised by _get_provider() when an unsupported provider name is given
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(exc),
        ) from exc
    except Exception as exc:
        logger.exception(f"Unexpected error generating estimation: {exc}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An unexpected error occurred while generating the estimation. Please try again.",
        ) from exc
