"""Estimation router — handles POST /api/v1/estimate."""

from fastapi import APIRouter, status

from src.schemas.estimation import EstimationRequest, EstimationResponse
from src.services.llm_service import generate_estimation

router = APIRouter(prefix="/api/v1", tags=["Estimation"])


@router.post(
    "/estimate",
    response_model=EstimationResponse,
    status_code=status.HTTP_200_OK,
    summary="Generate a software effort estimation",
    description=(
        "Receives the raw text of a meeting transcription and returns a structured "
        "software effort estimation generated by an LLM using CAG (Context-Augmented Generation)."
    ),
)
async def estimate(request: EstimationRequest) -> EstimationResponse:
    """POST /api/v1/estimate

    FastAPI automatically:
    - Parses and validates the JSON body against EstimationRequest.
    - Returns 422 if validation fails (missing fields, wrong types, etc.).
    - Serialises the returned EstimationResponse to JSON.

    Domain exceptions (ProviderRateLimitError, ProviderAuthError, UnknownProviderError)
    are handled globally by the exception handlers registered in main.py.
    """
    return await generate_estimation(
        transcript=request.transcript,
        provider_override=request.provider,
    )
