"""Estimation router — handles POST /api/v1/estimate and POST /api/v1/estimate/stream."""

import json
from typing import Annotated

from fastapi import APIRouter, Depends, status
from fastapi.responses import StreamingResponse

from src.dependencies import get_estimation_service
from src.schemas.estimation import EstimationRequest, EstimationResponse
from src.services.estimation import EstimationService
from src.services.llm_service import (
    stream_estimation,
)
from src.prompts.loader import render_estimation_prompt

router = APIRouter(prefix="/api/v1", tags=["Estimation"])


@router.post(
    "/estimate",
    response_model=EstimationResponse,
    status_code=status.HTTP_200_OK,
    summary="Generate a software effort estimation",
    description=(
        "Receives the raw text of a meeting transcription and returns a structured "
        "software effort estimation generated by an LLM using CAG (Context-Augmented Generation)."
    ),
)
async def estimate(
    request: EstimationRequest,
    service: EstimationService = Depends(get_estimation_service),
) -> EstimationResponse:
    """POST /api/v1/estimate

    FastAPI automatically:
    - Parses and validates the JSON body against EstimationRequest.
    - Returns 422 if validation fails (missing fields, wrong types, etc.).
    - Serialises the returned EstimationResponse to JSON.

    Domain exceptions are handled globally by the exception handlers registered
    in main.py (InputGuardrailViolation → 400, InstructorRetryException → 502,
    UnknownProviderError → 400, etc.).
    """
    return await service.estimate(request)


@router.post(
    "/estimate/stream",
    status_code=status.HTTP_200_OK,
    summary="Generate a software effort estimation (streaming)",
    description=(
        "Streams the estimation as Server-Sent Events. Text chunks arrive as "
        "`data: <text>` lines. The final event is `data: [DONE]<json>` containing "
        "the full EstimationResponse metadata."
    ),
)
async def estimate_stream(
    request: EstimationRequest,
    prompt_version: Annotated[str, Query(pattern=r"^v[0-9]+$")] = "v1",
) -> StreamingResponse:
    """POST /api/v1/estimate/stream"""

    async def event_generator():
        async for chunk in stream_estimation(request, prompt_version=prompt_version):
            if isinstance(chunk, str):
                yield f"data: {chunk}\n\n"
            else:
                yield f"data: [DONE]{chunk.model_dump_json()}\n\n"

    return StreamingResponse(event_generator(), media_type="text/event-stream")


@router.get(
    "/context",
    status_code=status.HTTP_200_OK,
    summary="Return the active system prompt",
    description="Returns the full system prompt injected in every estimation request (CAG context).",
)
async def get_context() -> dict:
    """GET /api/v1/context"""
    from src.schemas.estimation import DetailLevel, OutputFormat, ProjectType

    dummy = EstimationRequest(
        description="Placeholder request used to render the active system prompt for inspection.",
        project_type=ProjectType.WEB_SAAS,
        detail_level=DetailLevel.MEDIUM,
        output_format=OutputFormat.PHASES_TABLE,
    )
    system, _ = render_estimation_prompt(dummy)
    return {"system_prompt": system}
